
apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-fullyfeatured-go-backend-with-telemetry.fullname" . }}
  labels:
    {{- include "test-fullyfeatured-go-backend-with-telemetry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "test-fullyfeatured-go-backend-with-telemetry.selectorLabels" . | nindent 4 }}
